# release-plz configuration
# https://release-plz.ieni.dev/docs/config

# Examples should not be released to crates.io
[[package]]
name = "my-app"
release = false
changelog_update = false

[[package]]
name = "my-app-db"
release = false
changelog_update = false

[[package]]
name = "my-app-queries"
release = false
changelog_update = false
