[package]
name = "dibs-sql"
version = "0.1.0"
edition = "2024"

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[dependencies]
indexmap = "2"

[dev-dependencies]
insta = "1"
